# PEP-621
[project]
name = "arbiter"
version = "0.1.0"
description = ""
readme = "README.md"
dependencies = [
    "fastapi >= 0.97.0",
    "uvicorn[standard] >= 0.22.0",
    "sqlmodel >= 0.0.8",
    "python-jose[cryptography] >= 3.3.0",
    "passlib[bcrypt] >= 1.7.4",
    "python-multipart >= 0.0.6",
    "pydantic[dotenv] >= 1.10.9",
    "python-dotenv >= 1.0.0",
    "aiosqlite >= 0.19.0",
    "greenlet >= 2.0.2",
    "pytest >= 7.4.0",
    "jinja2 >= 3.1.2",
    "gymnasium >= 0.29.0"
]

# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "arbiter"
version = "0.1.0"
description = ""
authors = ["kc-softmax"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.97.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
sqlmodel = "^0.0.8"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
pydantic = {extras = ["dotenv"], version = "^1.10.9"}
python-dotenv = "^1.0.0"
aiosqlite = "^0.19.0"
greenlet = "^2.0.2"
pytest = "^7.4.0"
jinja2 = "^3.1.2"
gymnasium = "^0.29.1"