[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["kc-softmax"]
readme = "README.md"
packages = [{include = "auth", from = "server"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.97.0"
uvicorn = {extras = ["standard"], version = "^0.22.0"}
sqlmodel = "^0.0.8"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-multipart = "^0.0.6"
pydantic = {extras = ["dotenv"], version = "^1.10.9"}
python-dotenv = "^1.0.0"
aiosqlite = "^0.19.0"
greenlet = "^2.0.2"
pytest = "^7.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"