
ARBITER_SERVICE_HEALTH_CHECK_INTERVAL = 4
ARIBTER_DEFAULT_RPC_TIMEOUT = 5
ARBITER_SERVICE_PENDING_TIMEOUT = 30
ARBITER_SERVICE_ACTIVE_TIMEOUT = 30
ARBITER_SERVICE_SHUTDOWN_TIMEOUT = 10
ARBITER_SERVICE_TIMEOUT = 10
ARBITER_SYSTEM_INITIAL_TIMEOUT = 10
ARBITER_SYSTEM_TIMEOUT = 30

ARBITER_SYSTEM_CHANNEL = "arbiter_system_channel"
ARBITER_API_CHANNEL = "arbiter_api_channel"
