from __future__ import annotations
from pydantic import BaseModel
from datetime import datetime
from .enums import *
from .messages import *

ALLOWED_TYPES = (BaseModel, list, int, str, float, bool, datetime)

WARP_IN_TIMEOUT = 10

ARBITER_SERVICE_HEALTH_CHECK_INTERVAL = 4
ARIBTER_DEFAULT_TASK_TIMEOUT = 5
ARBITER_SERVICE_PENDING_TIMEOUT = 20
ARBITER_SERVICE_ACTIVE_TIMEOUT = 30
ARBITER_SERVICE_SHUTDOWN_TIMEOUT = 10
ARBITER_SERVICE_TIMEOUT = 10
HEALTH_CHECK_RETRY = 3
ARBITER_SYSTEM_TIMEOUT = 30

ARBITER_API_SHUTDOWN_TIMEOUT = 10