from __future__ import annotations
from pydantic import BaseModel
from datetime import datetime
from .enums import *
from .messages import *

ALLOWED_TYPE = (BaseModel, int, str, float, bool, datetime)
AUTH_PARAMETER = "user_id"

WARP_IN_TIMEOUT = 10

ARBITER_SERVICE_HEALTH_CHECK_INTERVAL = 4
ARIBTER_DEFAULT_TASK_TIMEOUT = 5
ARBITER_SERVICE_PENDING_TIMEOUT = 20
ARBITER_SERVICE_ACTIVE_TIMEOUT = 30
ARBITER_SERVICE_SHUTDOWN_TIMEOUT = 10
ARBITER_SERVICE_TIMEOUT = 10
ARBITER_SYSTEM_TIMEOUT = 30

ARBITER_SYSTEM_CHANNEL = "arbiter_system_channel"
ARBITER_API_CHANNEL = "arbiter_api_channel"
ARBITER_API_SHUTDOWN_TIMEOUT = 10

GITHUB_CLIENT_ID = "Ov23liONY4KlSndH657e"
GITHUB_CLIENT_SECRET = "3a9e464a989f1a30d569fce567454d9fa4746f03"