from __future__ import annotations
from pydantic import BaseModel
from datetime import datetime

ALLOWED_TYPES = (BaseModel, list, int, str, float, bool, datetime)

ASYNC_TASK_CLOSE_MESSAGE = b'q__end__q'

PROJECT_NAME  = "arbiter"
CONFIG_FILE = "arbiter.setting.ini"

WARP_IN_TIMEOUT = 10

ARBITER_SERVICE_HEALTH_CHECK_INTERVAL = 4
ARIBTER_DEFAULT_TASK_TIMEOUT = 5
ARBITER_SERVICE_PENDING_TIMEOUT = 10
ARBITER_SERVICE_ACTIVE_TIMEOUT = 30
ARBITER_SERVICE_SHUTDOWN_TIMEOUT = 10
ARBITER_SERVICE_TIMEOUT = 10
HEALTH_CHECK_RETRY = 3
ARBITER_SYSTEM_TIMEOUT = 30

ARBITER_API_SHUTDOWN_TIMEOUT = 10